version: 0

# Fixed antenna station radios
fixedInitialRadius: 50
fixedRadiusIncreasePerBlock: 50
fixedLightningAttractRadiusInitial: 3
fixedLightningAttractRadiusIncreasePerBlock: 1
fixedLightningAttractRadiusMax: 6
fixedWeatherListener: true
# Explosive power when tower struck by lightning (ghast fireball=1, creeper=2, TNT=4)
fixedBlastPowerInitial: 2
fixedBlastPowerIncreasePerBlock: 0.4
fixedBlastPowerMax: 10
fixedBlastSetFire: true
fixedRadiusStormFactor: 0.7     # attenuate/amplify when has storm
fixedRadiusThunderFactor: 1.1   # attenuate/amplify when is thundering
fixedMaxHeightMeters: 0         # clamp antenna height
fixedBaseMinY: 0                # must build base above this level
#fixedBaseMinY: 64              # sea level
fixedBaseMaterial: iron_block
#fixedBaseMaterial: jukebox
fixedAntennaMaterial: iron_fence
#fixedRadiateFrom: base
fixedRadiateFrom: tip
fixedUnpoweredNagMessage: 'Tip: remove and place this block near redstone current to build an antenna'
#fixedUnpoweredNagMessage: ''

# Mobile compass radios
mobileInitialRadius: 0
mobileIncreaseRadius: 10
mobileTaskStartDelaySeconds: 0
mobileTaskPeriodSeconds: 15
