version: 1

# Fixed antenna station radios
fixedInitialRadius: 100
fixedRadiusIncreasePerBlock: 100
fixedMaxHeightMeters: 0

# Portable compass radios
compassRadius: 10
compassTaskStartDelaySeconds: 0
compassTaskPeriodSeconds: 20
