version: 1

# Fixed antenna station radios
fixedInitialRadius: 50
fixedRadiusIncreasePerBlock: 50
fixedMaxHeightMeters: 0         # clamp antenna height
fixedBaseMinY: 0                # must build base above this level
#fixedBaseMinY: 64              # sea level
fixedBaseMaterial: iron_block
#fixedBaseMaterial: jukebox
fixedAntennaMaterial: iron_fence

# Portable compass radios
compassRadius: 10
compassTaskStartDelaySeconds: 0
compassTaskPeriodSeconds: 20
