name: RadioBeacon
main: me.exphc.RadioBeacon.RadioBeacon
version: 0.8.1
commands: 
    antennas:
        description: Show all antennas
        usage: /antennas
permissions:
    radiobeacon.*:
        children:
            radiobeacon.reveal: true
            radiobeacon.admin: true
        default: false
    radiobeacon.reveal:
        description: Allows you to list the coordinates of all antennas
        default: op
    radiobeacon.admin:
        description: Allows you to repair or save/load antennas from disk
        default: op
