name: RadioBeacon
main: me.exphc.RadioBeacon.RadioBeacon
version: 0.9
description: build radio towers, navigate to them using compasses
url: http://dev.bukkit.org/server-mods/radiobeacon/
commands: 
    antennas:
        description: Show all antennas
        usage: /antennas
permissions:
    radiobeacon.*:
        children:
            radiobeacon.reveal: true
            radiobeacon.admin: true
        default: false
    radiobeacon.reveal:
        description: Allows you to list the coordinates of all antennas
        default: op
    radiobeacon.admin:
        description: Allows you to save/load/check antennas
        default: op
