name: RadioBeacon
main: com.exphc.RadioBeacon.RadioBeacon
version: 1
commands: 
    antennas:
        description: Show all antennas
        usage: /antennas
permissions:
    radiobeacon.*:
        children:
            radiobeacon.reveal: true
        default: false
    radiobeacon.reveal:
        description: Allows you to list the coordinates of all antennas
        default: false
